#!/bin/bash

set -e

# set -u or set -o nounset
# set +u

# : command that takes no arguments, always return 0, i.e. true

# TODO(Ryan): Just use [[ ]]; in ifs

# TODO(Ryan): Perhaps introduce a diagnostic flag for c program builds as well

# lines=()
# read_entire_file "text-rand.txt" "lines"
# printf "%s\n" "${lines[@]}"
read_entire_file()
{
  local file_name="$1"
  local result_var="$2"

  local __read_entire_file_lines=()

  while IFS=$'\r\n' read -r line; do
    __read_entire_file_lines+=("$line")
  done < "$file_name"

  command eval "$result_var"'=(${__read_entire_file_lines[@]})' 
}

os="undefined"
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  os="linux"
fi

set -u
source "ignored/build-params"
declare -A build_params
build_params[compiler]=$compiler 
build_params[mode]=$mode 
build_params[linker]=$linker 
build_params[arch]=$arch
set +u

compiler_flags=()
linker_flags=()

if [[ "$compiler" == "gcc" ]]; then
  if [[ "$mode" == "debug" ]]; then
    flags+=( "-DMAIN_DEBUG" )

# pragma warning(disable: 4201) // nonstandard extension used: nameless struct/union

#	-@find $(BUILD) -name '*.gcda' -exec rm {} +
#	./$(EXECUTABLE)
#	@gcov -b -o $(BUILD)/src/ pugixml.cpp.gcda | sed -e '/./{H;$!d;}' -e 'x;/pugixml.cpp/!d;'
#	@find . -name '*.gcov' -and -not -name 'pugixml.cpp.gcov' -exec rm {} +
#	@sed -i -e "s/#####\(.*\)\(\/\/ unreachable.*\)/    1\1\2/" pugixml.cpp.gcov


-g -Wall -Wextra -Werror -pedantic -Wundef -Wshadow -Wcast-align -Wcast-qual -Wold-style-cast -Wdouble-promotion
--coverage (only for test builds)
-fanalyzer (static analysis)
-fsanitize=address,undefined -fno-sanitize=float-divide-by-zero,float-cast-overflow -fno-sanitize-recover=all
-fno-exceptions
  fi
  if [[ "$mode" == "release" ]]; then
-O3 -DNDEBUG
  fi

  gcc main.c -c main.o  
fi
if [[ "$linker" == "lld" ]]; then
  if [[ "$mode" == "debug" ]]; then
-coverage
-fsanitize=address,undefined
  fi
  if [[ "$mode" == "release" ]]; then

  fi

  lld main.o -o 
fi

# use bash as build script as is effectively OS agnostic 
# (if you have git on windows, you have bash)

# 2. IMPLICIT (things that are different to different users of the codebase)
# TODO(Ryan): Perhaps just set bash flag to error out on variables being undefined?
# put build params here to prevent many users having to include
# main_compiler="gcc"; compile_mode="debug"; linker="ldd"; arch="x64"
# lib_compiler="gcc"; lib_output="library"
