#!/bin/bash

set -eou pipefail

abs_file=$(realpath "$0")
abs_directory=$(dirname "$abs_file")

pushd "$abs_directory" >/dev/null

if [[ $# < 1 ]]; then
  gnuplot -c plot.gp *.metric
else
  gnuplot -c plot.gp "$@"
fi

xdg-open metrics.png

popd >/dev/null
